# Generated by Django 3.1.2 on 2020-10-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeAPIResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoID', models.CharField(max_length=40)),
                ('videoTitle', models.CharField(max_length=400, null=True)),
                ('videoDescription', models.CharField(blank=True, max_length=4000, null=True)),
                ('publishedAt', models.DateTimeField()),
                ('thumbnailURL', models.URLField()),
                ('thumbnailHeight', models.IntegerField()),
                ('thumbnailWidth', models.IntegerField()),
                ('channelTitle', models.CharField(max_length=400)),
            ],
        ),
    ]
